version: "3.9"
services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST}:5000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db: {}
