"""empty message

Revision ID: 053eca62a931
Revises: 
Create Date: 2024-05-25 18:16:38.189682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053eca62a931'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='amount_positive_check'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('telegram_username', name='unique_telegram_username')
    )
    op.create_table('chats',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('reward', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['groups.group_name'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('date_index', 'events', ['date'], unique=False)
    op.create_table('users_groups',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['groups.group_name'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id', 'group_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_groups')
    op.drop_index('date_index', table_name='events')
    op.drop_table('events')
    op.drop_table('chats')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
