"""empty message

Revision ID: 5ded53ffce20
Revises: 053eca62a931
Create Date: 2024-06-02 02:00:42.238953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ded53ffce20'
down_revision: Union[str, None] = '053eca62a931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('remaining_items', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('cost >= 0', name='cost_positive_check'),
    sa.CheckConstraint('remaining_items >= 0 or remaining_items is null', name='remaining_items_positive_check'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('purchases',
    sa.Column('purchase_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Ordered', 'Received', 'Cancelled', name='purchasestatus'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index('created_at_index', 'purchases', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('created_at_index', table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('products')
    # ### end Alembic commands ###
