"""empty message

Revision ID: e5fa58613132
Revises: 5ded53ffce20
Create Date: 2024-06-02 09:45:13.784102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fa58613132'
down_revision: Union[str, None] = '5ded53ffce20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchases_product_id_fkey', 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key('purchases_product_id_fkey', 'purchases', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
