"""empty message

Revision ID: efc2663bc435
Revises: 109e0089e2b1
Create Date: 2024-05-15 16:35:05.871920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc2663bc435'
down_revision: Union[str, None] = '109e0089e2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('date_index', 'events', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('date_index', table_name='events')
    # ### end Alembic commands ###
