"""empty message

Revision ID: f2e155841e1d
Revises: efc2663bc435
Create Date: 2024-05-24 16:15:10.372521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e155841e1d'
down_revision: Union[str, None] = 'efc2663bc435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['user_id'], ondelete='cascade')
    op.drop_constraint('events_group_name_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'groups', ['group_name'], ['group_name'], ondelete='cascade')
    op.drop_constraint('users_groups_group_name_fkey', 'users_groups', type_='foreignkey')
    op.drop_constraint('users_groups_user_id_fkey', 'users_groups', type_='foreignkey')
    op.create_foreign_key(None, 'users_groups', 'groups', ['group_name'], ['group_name'], ondelete='cascade')
    op.create_foreign_key(None, 'users_groups', 'users', ['user_id'], ['user_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_groups', type_='foreignkey')
    op.drop_constraint(None, 'users_groups', type_='foreignkey')
    op.create_foreign_key('users_groups_user_id_fkey', 'users_groups', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('users_groups_group_name_fkey', 'users_groups', 'groups', ['group_name'], ['group_name'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_group_name_fkey', 'events', 'groups', ['group_name'], ['group_name'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
